apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
  name: job-check-lvm
  namespace: {{ .Values.minio.namespace }} 
spec:
  template:
    spec:
      containers:
      - env:
        - name: "HTTP_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "HTTPS_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "NO_PROXY"
          value: "mgmt.npss.bos2.lab,10.128.0.0/14,,172.30.0.0/16,172.31.1.0/24"  
          name: lvm-status-check
        image: quay.io/sfhassan/oc_net_tools
        command:
        - /bin/bash
        - -c
        - |
          echo "### Only proceed if LVM is installed  ..."
          lvmready=0
          while [ $lvmready -lt 1 ]; do 
            lvmready=$(oc get deployment -n {{ .Values.storageNS }}  lvms-operator -o json | jq .status.availableReplicas)
            echo "Waiting for LVM operator to be ready...currently seeing pods: " $lvmready
            sleep 10
          done 
          echo "LVM is ready..."
          echo "Now wating till a default storage class exists"
          defaultexists=0
          while [ $defaultexists != 1 ]; do
            defaultexists=$(oc get sc | grep -c default)
            echo "waiting...."
            sleep 10
          done
          echo "Ensuring there is at least one PV created..."
          pvcount=0
          while [ $pvcount -lt 1 ]; do 
            pvcount=$(oc get pv --no-headers | wc -l)
            echo "waiting...."
            sleep 10
          done
          echo "Done..."
        name: lvm-status-check
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: {{ .Values.minio.sa }}
      terminationGracePeriodSeconds: 60
