apiVersion: v1 
kind: PersistentVolume 
metadata: 
 name: pv-analytics 
spec: 
  istorageClassName: lvms-vg1
  capacity: 
    storage: 50Gi 
  accessModes: 
  - ReadWriteMany
  volumeMode: Filesystem 
  hostPath: 
    path: /pv
