
#file name depends   clusterGroupName in values-global.yaml

clusterGroup:
  name: hub
  isHubCluster: true
  common:
    storageNS: openshift-storage
  namespaces:
  - openshift-cnv
  - mgmt-apps           # creating early to enable NAD to be created by nmstate
  - openshift-nmstate  
  - minio
  - open-cluster-management #for ACM
    # - openshift-local-storage
    # - openshift-storage  
    # - quay-enterprise
    #  - openshift-operators-redhat
    #  - openshift-logging  
    #- openshift-operators-redhat
    #- prom-kafka-adapter 
    #- edge-gitops-vms
    #- mano-automation
    #- ansible
  subscriptions:
    cnv:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      installPlanApproval: Automatic
      channel: "stable"

    nmstate:
      name: kubernetes-nmstate-operator
      namespace: openshift-nmstate  
    
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      installPlanApproval: Manual
        #    lso:
        #      name: local-storage-operator
        #      namespace: openshift-local-storage
        #
        #    odf:
        #      name: odf-operator
        #      namespace: openshift-storage  
    # 
    #
    #    quay:
    #      name: quay-operator
    #      namespace: quay-enterprise    
    #        #channel: stable-3.7
    #
    #
    #    prometheus:
    #      name: prometheus
    #      namespace: service-telemetry    
    #      channel: beta
    #      source: community-operators
    # 
    #    kafka:
    #      name: amq-streams
    #      namespace: kafka-cluster 
    #   
    #    elasticsearch:
    #      name: elasticsearch-operator
    #      namespace: openshift-operators-redhat

        #    logging:
        #      name: cluster-logging
        #      namespace: openshift-logging
        #   
        #    pao:
        #      name: performance-addon-operator
        #      namespace: openshift-performance-addon-operator    

        #talam:
        #  name: topology-aware-lifecycle-manager
        #  namespace: openshift-operators 

        #    ansible:
        #      name: ansible-automation-platform-operator
        #      namespace: ansible 
        #      source: redhat-operators
        #      channel: stable-2.3

#     disable: true

#    kubevirt-hyperconverged:
#      name: kubevirt-hyperconverged
#      namespace: openshift-cnv
#      source: redhat-operators
#      channel: stable

  projects:
  - hub
  - hub-storage

  applications:
    cnv:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      path: charts/mgt-hub/cnv  
      project: hub
    nmstate:
      name: nmstate-crd
      namespace: openshift-nmstate
      path: charts/mgt-hub/nmstate  
      project: hub
    minio:
      name: minio
      namespace: minio 
      path: charts/mgt-hub/minio
      project: hub-storage
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: charts/mgt-hub/acm
        #    lso:
        #      name: local-storage 
        #      namespace: openshift-local-storage
        #      path: charts/mgt-hub/lso
        #      project: hub  
        #
        #    odf:
        #      name: odf
        #      namespace: openshift-storage
        #      path: charts/mgt-hub/openshift-data-foundations  
        #      project: hub-storage
        #    quay:
        #      name: quay
        #      namespace: quay-enterprise
        #      path: charts/mgt-hub/quay
        #      project: hub
    #
        #
            #    kafka:
            #      name: kafka
            #      namespace: kafka-cluster
            #      path: charts/mgt-hub/kafka
            #      project: hub
            #
            #    monitoring:
            #      name: monitoring
            #      namespace: prom-kafka-adapter
            #      path: charts/mgt-hub/monitoring
            #      project: hub  
            #
            #    logging:
            #      name: logging
            #      namespace: openshift-logging
            #      path: charts/mgt-hub/logging
            #      project: hub
            #  
            #    edge-gitops-vms:
            #      name: edge-gitops-vms
            #      namespace: edge-gitops-vms
            #      project: hub
            #      path: charts/mgt-hub/edge-gitops-vms
            #
            #    mc:    
            #      name: mc
            #      path: charts/mgt-hub/mc  
            #      project: hub
            #
            #    ansible:
            #      name: ansible
            #      path: charts/mgt-hub/ansible
            #      project: hub
            #
            #
            #


