
#file name depends   clusterGroupName in values-global.yaml
global:
  quay_fqdn: quay-registry-quay-quay-enterprise.apps.mgmt.npss.bos2.lab

clusterGroup:
  name: hub
  isHubCluster: true
  namespaces:
  - openshift-cnv
  - mgmt-apps                 # creating early to enable NAD to be created by nmstate
  - openshift-nmstate  
    #- openshift-local-storage   # only needed if using LSO. Not needed for SNO case
  - openshift-storage         # needed either by LVM, or LSO/ODF combo
    # - minio                     # only needed if ODF is not being used, as in SNO's case
  - open-cluster-management   #for ACM
    # NS for non automated items:
    #- quay-enterprise              #for Quay
    #- openshift-operators-redhat   #for elasticsearch
    #- openshift-logging            #for logging
    #- prom-kafka-adapter           #for Kafka
    #- kafka-cluster                #for Kafka
    #- ansible                      #for ansible
  subscriptions:
    cnv:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      installPlanApproval: Automatic
      channel: "stable"

    nmstate:
      name: kubernetes-nmstate-operator
      namespace: openshift-nmstate  
      channel: stable
    
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.8
      installPlanApproval: Manual
    ## If SNO --> use LVM Operator, and enable application for LVM as well as Minio
    lvm:  
      name: lvms-operator
      namespace: openshift-storage
      channel: stable-4.12
    ## If !SNO --> use LSO and ODF Operator, and enable tha respective apps *instead*
        # 
        #    lso:
        #      name: local-storage-operator
        #      namespace: openshift-local-storage
        #
        #    odf:
        #      name: odf-operator
        #      namespace: openshift-storage  
        #    quay:
        #      name: quay-operator
        #      namespace: quay-enterprise    
        #      channel: stable-3.9
        # 
        #    kafka:
        #      name: amq-streams
        #      namespace: kafka-cluster 
        #      channel: stable
        #   
        #    elasticsearch:
        #      name: elasticsearch-operator
        #      namespace: openshift-operators-redhat
        #      channel: stable
        #
        #    logging:
        #      name: cluster-logging
        #      namespace: openshift-logging
        #      channel: stable
        #   
        #    talm:
        #      name: topology-aware-lifecycle-manager
        #      namespace: openshift-operators 
        #      channel: stable
        #    ansible:
        #      name: ansible-automation-platform-operator
        #      namespace: ansible 
        #      source: redhat-operators
        #      channel: stable-2.4
#     disable: true
        #    prometheus:
        #      name: prometheus
        #      namespace: service-telemetry    
        #      channel: beta
        #      source: community-operators

  projects:
  - hub
  - hub-storage
  - hub-apps

  applications:
    cnv:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      path: charts/mgt-hub/cnv  
      project: hub
    nmstate:
      name: nmstate-crd
      namespace: openshift-nmstate
      path: charts/mgt-hub/nmstate  
      project: hub
    ## If SNO --> use LVM Operator, and enable application for LVM as well as Minio
    ## If !SNO --> use LSO and ODF Operator, and enable tha respective apps *instead*
    ############
    #  SNO
    ############
    #    lvm:
    #      name: lvm
    #      namespace: opebshift-stoage 
    #      path: charts/mgt-hub/lvm
    #      project: hub-storage
    #    minio:
    #      name: minio
    #      namespace: minio 
    #      path: charts/mgt-hub/minio
    #      project: hub-storage
    ############
    #  !SNO
    ############
        #    lso:
        #      name: local-storage 
        #      namespace: openshift-local-storage
        #      path: charts/mgt-hub/lso
        #      project: hub  
        #
        #    odf:
        #      name: odf
        #      namespace: openshift-storage
        #      path: charts/mgt-hub/openshift-data-foundations  
        #      project: hub-storage
    ### end of SNO diversion ###
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: charts/mgt-hub/acm
        #    quay:
        #      name: quay
        #      namespace: quay-enterprise
        #      path: charts/mgt-hub/quay
        #      project: hub-apps
        #
        #    kafka:
        #      name: kafka
        #      namespace: kafka-cluster
        #      path: charts/mgt-hub/kafka
        #      project: hub
        #
        #    monitoring:
        #      name: monitoring
        #      namespace: prom-kafka-adapter
        #      path: charts/mgt-hub/monitoring
        #      project: hub  
        #
        #    logging:
        #      name: logging
        #      namespace: openshift-logging
        #      path: charts/mgt-hub/logging
        #      project: hub
        #  
        #    ansible:
        #      project: hub


