apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "25"
  name: prequel-job-discovered-volumes
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          # before we run the main LSO check job, first need to ensure the the user in LSO has been created
          # We do however know (since this job is PreSync#5 that the ODF's SA has already been created 
          # since that is PreSync#-15 
          # So its safe to run as that ODF user to check on cluster level role bindings and see if 
          # LSO binding existis
          oc wait clusterrolebindings/{{ .Values.lso.bindname }} --for=jsonpath='{.roleRef.name}'={{ .Values.lso.bindrole | squote }}
        name: prequel-job-discovered-volumes
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.lso.jobTerminationGracePeriod }}
