apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "30"
  name: oc-mirror-plugin
  namespace: quay-enterprise
spec:
  template:
    spec:
      containers:
      - env:
        - name: "HTTP_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "HTTPS_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "NO_PROXY"
          value: "mgmt.npss.bos2.lab,10.128.0.0/14,,172.30.0.0/16,172.31.1.0/24"  
        name: for-mirroring
        image: quay.io/sfhassan/oc_net_tools
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "20000Mi"
            cpu: "2"    
        command:
        - /bin/bash
        - -c
        - |
          while true; do sleep 10; done
        name: oc-mirror-plugin
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: cli-job-sa
        #serviceAccountName: quay-admin-sa
      terminationGracePeriodSeconds: 60
