apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: sno-lvmcluster
  namespace: {{ .Values.storageNS }}
spec:
  storage:
    deviceClasses:
    - name: vg1
      deviceSelector: 
        paths: 
        - /dev/sdb
      thinPoolConfig:
        name: thin-pool-1
        overprovisionRatio: 10
        sizePercent: 90
