# Container image used by deployment/pods
minio:
  namespace: minio
  sa: minio-sa
image: "quay.io/minio/minio"
namespace: minio
size: 100Gi
ingress:
  # MinIO API DNS name. This is the S3 API.  Don't prefix with "https://"
  minioApiDnsName: "minio.apps.mgmt2.npss.bos2.lab"
  # MinIO Console DNS name. This is a management web console. Don't prefix
  # with "https://"
  minioConsoleDnsName: "minio-console.apps.mgmt2.npss.bos2.lab"

# user.accessKey and user.secretAccessKey are used to log into both the S3 API
# and the web management console.
# Hint: Access key length should be at least 3, and secret key length at least 8 characters
user:
  accessKey: "minio"
  secretAccessKey: "minioredhat"
