apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: acm-approve-install-plan
  namespace: {{ .Values.acm.namespace }} 
spec:
  template:
    spec:
      containers:
      - env:
        - name: "HTTP_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "HTTPS_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "NO_PROXY"
          value: "mgmt.npss.bos2.lab,10.128.0.0/14,,172.30.0.0/16,172.31.1.0/24"  
        name: acm-install-plan-approve
        image: quay.io/sfhassan/oc_net_tools
        command:
        - /bin/bash
        - -c
        - |
          echo "### Finding unapproved Install plans..."
          planspending=$(oc get ip -n {{ .Values.acm.namespace }}  -o=jsonpath='{.items[?(@.spec.approved==false)].metadata.name}')
          echo "Found:"
          echo $planspending
          echo "Approving these..."
          oc patch installplan $planspending -n {{ .Values.acm.namespace }} --type merge --patch '{"spec":{"approved":true}}'
          echo "Done..."
          sleep 1000
        name: acm-install-plan-approve
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: {{ .Values.acm.sa }}
      terminationGracePeriodSeconds: 60
