apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: ocs-storagecluster-ceph-rbd
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: ocs-storagecluster-ceph-rbd
  mirrorRegistryRef:
    name: mirror-registry-config-map
  osImages:
    - openshiftVersion: "4.12"
      version: 412.86.202303241612-0
      url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/4.12.10/rhcos-4.12.10-x86_64-live.x86_64.iso
      rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/4.12.10/rhcos-4.12.10-x86_64-live-rootfs.x86_64.img
      cpuArchitecture: "x86_64"
  unauthenticatedRegistries:
  - '*.{{ domain }}'
