---
# Source: acm/templates/00-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acm-cli-sa 
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-20"
---
# Source: acm/templates/30-mirror_cm.yaml
apiVersion: v1
data:
  mirror-list: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
       prefix = ""
       location = "registry.redhat.io/multicluster-engine"
       mirror-by-digest-only = true

       [[registry.mirror]]
       location = "quay-registry-quay-quay-enterprise.apps.mgmt.npss.bos2.lab/ocp/ocp4/multicluster-engine"

    [[registry]]
       prefix = ""
       location = "quay.io/openshift-release-dev/ocp-release"
       mirror-by-digest-only = true

       [[registry.mirror]]
       location = "quay-registry-quay-quay-enterprise.apps.mgmt.npss.bos2.lab/ocp/ocp4/openshift/release-images"

    [[registry]]
       prefix = ""
       location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
       mirror-by-digest-only = true

       [[registry.mirror]]
       location = "quay-registry-quay-quay-enterprise.apps.mgmt.npss.bos2.lab/ocp/ocp4/openshift/release"
kind: ConfigMap
metadata:
  name: temp
  namespace: multicluster-engine
  annotations:
    argocd.argoproj.io/sync-wave: "30"
---
# Source: acm/templates/00-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acm-cli-sa-rolebinding
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: acm-cli-sa
    namespace: open-cluster-management
---
# Source: acm/templates/10-job-approve-install-plans.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: acm-approve-install-plan
  namespace: open-cluster-management 
spec:
  template:
    spec:
      containers:
      - env:
        - name: "HTTP_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "HTTPS_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "NO_PROXY"
          value: "mgmt.npss.bos2.lab,10.128.0.0/14,,172.30.0.0/16,172.31.1.0/24"  
        name: acm-install-plan-approve
        image: quay.io/sfhassan/oc_net_tools
        command:
        - /bin/bash
        - -c
        - |
          echo "### Finding unapproved Install plans..."
          planspending=$(oc get ip -n open-cluster-management  -o=jsonpath='{.items[?(@.spec.approved==false)].metadata.name}')
          echo "Found:"
          echo $planspending
          echo "Approving these..."
          oc patch installplan $planspending -n open-cluster-management --type merge --patch '{"spec":{"approved":true}}'
          echo "Done..."
        name: acm-install-plan-approve
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: acm-cli-sa
      terminationGracePeriodSeconds: 60
---
# Source: acm/templates/25-multicluster-IP-approval.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  name: multicluaster-engine-approve-install-plan
  namespace: open-cluster-management 
spec:
  template:
    spec:
      containers:
      - env:
        - name: "HTTP_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "HTTPS_PROXY"
          value: "http://192.168.32.4:3128"
        - name: "NO_PROXY"
          value: "mgmt.npss.bos2.lab,10.128.0.0/14,,172.30.0.0/16,172.31.1.0/24"  
        name: multicluaster-engine-approve-install-plan
        image: quay.io/sfhassan/oc_net_tools
        command:
        - /bin/bash
        - -c
        - |
          echo "### Finding unapproved Install plans for Multicluster-Engine..."
          echo "...giving 30 seconds for MCE Install Plan to be created first ... "
          # NS for MCE is usually multicluster-engine, but putting as variable just in case
          count=0
          while [ $count == 0 ]; do
            planspending=$(oc get ip -n multicluster-engine  -o=jsonpath='{.items[?(@.spec.approved==false)].metadata.name}')
            count=$(echo $planspending | wc -w)
            echo "still waiting for IP...."
            echo "Found: "; echo $planspending
            echo "Count: "; echo $count
            sleep 10
          done
          echo "Found:"
          echo $planspending
          echo "Approving these..."
          oc patch installplan $planspending -n multicluster-engine --type merge --patch '{"spec":{"approved":true}}'
          echo "Done..."
        name: multicluaster-engine-approve-install-plan
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: acm-cli-sa
      terminationGracePeriodSeconds: 60
---
# Source: acm/templates/20-multiclusterhub.yaml
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    installer.open-cluster-management.io/mce-subscription-spec: '{"installPlanApproval": "Manual", "source": "redhat-operators" }'
spec: {}
---
# Source: acm/templates/35-provisioning-config.yaml
# Needed as per : https://issues.redhat.com/browse/METAL-54
apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
spec:
  provisioningNetwork: "Disabled"
  watchAllNamespaces: true
