param:
  SUPER_USERS:
  - quayadmin
  FEATURE_USER_INITIALIZE: true
  BROWSER_API_CALLS_XHR_ONLY: false
  #FEATURE_USER_CREATION: false
  ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
  DEFAULT_TAG_EXPIRATION: 2w
  ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
  FEATURE_BUILD_SUPPORT: false
  FEATURE_DIRECT_LOGIN: true
  FEATURE_MAILING: false
  FEATURE_REPO_MIRROR: true
  REPO_MIRROR_INTERVAL: 30
  REPO_MIRROR_SERVER_HOSTNAME: quay-registry-quay-quay-enterprise.apps.mgmt2.npss.bos2.lab 
  REPO_MIRROR_TLS_VERIFY: false
  REPO_MIRROR_ROLLBACK: true
  REGISTRY_TITLE: Red Hat Quay
  REGISTRY_TITLE_SHORT: Red Hat Quay
  TAG_EXPIRATION_OPTIONS:
  - 2w
  TEAM_RESYNC_STALE_TIME: 60m
  TESTING: false
  AUTHENTICATION_TYPE: Database
  FEATURE_USER_CREATION: true
  #allow user creations by non super users
  REPO_MIRROR_TLS_VERIFY: false
  REPO_MIRROR_ROLLBACK: true
  CREATE_NAMESPACE_ON_PUSH: true
  # auto create org if not exist when pushing
  FEATURE_GENERAL_OCI_SUPPORT: true
  #
quay:
  namespace: quay-enterprise
  fqdn: quay.apps.mano-npss.jnpr.bos2.lab
  configBundleSecret:
    deploy: true
    name: quay-init-config-bundle-secret
  components:
    - kind: clair
      managed: true
    - kind: postgres
      managed: true
    - kind: objectstorage
      managed: true
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: false

    #
    # HERE
  setup:
    admin:
      # Generated password is saved to the 'quay-init-token' secret in the configured namespace
      name: quayadmin
      email: quayadmin@example.com
    user:
      # Generated password is saved to the 'quay-user' secret in the configured namespace
      # The API only allows the creation of superusers
      name: developer1
      email: developer1@myorg.com

job:
  image: quay.io/sfhassan/oc_net_tools
    # quay_hostname: quay-registry-quay-quay-enterprise.apps.mgmt.npss.bos2.lab
  quay_user: quay
  quay_passwd: registry

global:
  hub:
    clustername: NAME
    domain: DOMAIN

  quay:
    org:
      name: devel
      email: devel@myorg.com
    repo: example

clusterGroup:
  name: AUTOMATIC
