apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: patterns-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/patterns-operator.openshift-operators: ""
spec:
  channel: fast
  installPlanApproval: Automatic
  name: patterns-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ebc-multicloud-gitops
  namespace: openshift-operators
spec:
  clusterGroupName: hub
  gitOpsSpec:
    operatorChannel: gitops-1.8
    operatorSource: redhat-operators
  gitSpec:
    targetRepo: https://github.com/git-shassan/syed-vpattern.git
    targetRevision: master
apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
